name: Destroy AWS EKS Infrastructure

on:
  workflow_dispatch: # Permite rodar manualmente

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_BACKEND_BUCKET: hiagogouveia-eks-tfstate-XXXX # <- SEU NOME AQUI

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # CORREÇÃO: Passar o Secret diretamente
          aws-region: ${{ secrets.AWS_REGION }} 
          role-duration-seconds: 900

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" -backend-config="dynamodb_table=terraform-locks" -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve